name: project2
channels:
  - conda-forge
dependencies:
  - adaptive
  - pfapack
  - pipefunc
  - pip: markdown-code-runner
  - pip: home-assistant-streamdeck-yaml
includes:
  - ../project3  # depends on project3
