name: setup_py_project
channels:
  - conda-forge
dependencies:
  - pandas
  - adaptive >=0.15.0, <2.0.0
  - pip: yaml2bib # [linux64]
  - pip: rsync-time-machine
  - pip: slurm-usage
  - pip: fileup  # [macos]
  - pip: pyyaml
  - pip: aiokef
local_dependencies:
  - ../setuptools_project  # depends on setuptools_project
platforms:
  - linux-64
  - osx-64
  - osx-arm64
