name: hatch_project
channels:
  - conda-forge
dependencies:
  - adaptive-scheduler  # [linux64]
  - pip: unidep
  - numpy >=1.22
  - hpc05  # [linux64]
  - pandas >=2,<3
  - pexpect # [unix]
  - wexpect # [win]
