name: project1
channels:
  - conda-forge
dependencies:
  - pandas
  - pip: adaptive >=1.0.0
  - pip: yaml2bib # [linux64]
  - pip: rsync-time-machine
  - pip: slurm-usage
  - pip: fileup  # [macos]
  - pip: codestructure
  - pip: aiokef
