name: setuptools_project
channels:
  - conda-forge
dependencies:
  - adaptive
  - pfapack  # [linux64]
  - pipefunc
  - pip: markdown-code-runner
  - pip: home-assistant-streamdeck-yaml
local_dependencies:
  - ../hatch_project  # depends on hatch_project
