name: setuptools_project
channels:
  - conda-forge
dependencies:
  - adaptive
  - pfapack  # [linux64]
  - pipefunc
  - pip: markdown-code-runner
  - pip: numthreads
local_dependencies:
  - ../hatch_project[test]  # depends on hatch_project
optional_dependencies:
  dev:
    - mypy
    - ruff
  test:
    - pytest-xdist
  setup_py:
    # Optional local dependency
    - ../setup_py_project
