name: setuptools_project
channels:
  - conda-forge
dependencies:
  - adaptive
  - pfapack
  - pipefunc
  - pip: markdown-code-runner
  - pip: home-assistant-streamdeck-yaml
includes:
  - ../hatch_project  # depends on hatch_project
