name: pip-install

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pip-install:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    env:
      PYTHONIOENCODING: "utf8" # https://gist.github.com/NodeJSmith/e7e37f2d3f162456869f015f842bcf15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pyproject.toml
        run: |
          python .github/use-local-unidep.py
      - name: Install example packages
        run: |
          # Loop over all folders in `./example` and install them
          for d in ./example/*/ ; do
            pip install -e "$d"
          done

  conda-install:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    env:
      PYTHONIOENCODING: "utf8" # https://gist.github.com/NodeJSmith/e7e37f2d3f162456869f015f842bcf15
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: unidep
          create-args: >-
            python=${{ matrix.python-version }}
      - name: Install unidep
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[toml]"
        shell: bash -el {0}
      - name: Install example packages
        run: |
          # Loop over all folders in `./example` and install them
          for d in ./example/*/ ; do
            unidep install -e "$d"
          done
